### ISSUE TITLE
Forwarding stopped working

### ISSUE THREAD

**Issue by lucaseverett** [forwardemail/free-email-forwarding-service#175]
Is there an issue this morning? I first noticed something was wrong when I didn't receive an email for an Amazon order this morning, so I sent myself test emails to two different email addresses I'm forwarding through this service, and neither have been received. I'm using a Gmail address for the forward. Is it possible Gmail isn't delivering the emails to me, or is it something with the forwarding server?

Note: The last email I received from the forwarding service was at 9:44 AM CT.

**Comment by lucaseverett** [comment]
As of 12:08 PM CT I'm starting to receive emails from Amazon again, though none of the ones from this morning were ever delivered, and I'm still not receiving any emails that I send to myself from my work email address to the addresses that are being forwarded.

Is this an issue with the forwarding service? I'm concerned at this point that Gmail is blocking some emails from the forwarding server from being delivered to my inbox.

No emails at all were delivered to my inbox between 9:44 AM to 12:08 PM, including spam messages. I typically receive spam all throughout the day, but today there was that block of time that no messages were received

**Comment by lucaseverett** [comment]
I did a test from https://ismyemailworking.com/AdvancedTest/ and got the following errors.

10/05/2019 06:10:42 - [IsMyEmailWorking.com email test started]
10/05/2019 06:10:45 - [Querying DNS for responsible mail servers for 'lucaseverett.email']
10/05/2019 06:10:45 - [Starting DNS Session]
10/05/2019 06:10:45 - [RFC 5321 5. The lookup first attempts to locate an MX record associated with the name. If a CNAME record is found, the resulting name is processed as if it were the initial name. If no MX records are found, but an A RR is found, the A RR is treated as if it was associated with an implicit MX RR, with a preference of 0, pointing to that host.]
10/05/2019 06:10:45 - [Trying to get MX Records for 'lucaseverett.email']
10/05/2019 06:10:45 - [Found MX Record 'mx1.forwardemail.net' Preference '10']
10/05/2019 06:10:45 - [Found MX Record 'mx2.forwardemail.net' Preference '20']
10/05/2019 06:10:45 - [Found 2 MX Records]
10/05/2019 06:10:45 - [Searching Found MX Records for Host Records]
10/05/2019 06:10:45 - [MX Record 'mx1.forwardemail.net' Did not include any Host records. Queueing 'mx1.forwardemail.net' for further resolution.]
10/05/2019 06:10:45 - [MX Record 'mx2.forwardemail.net' Did not include any Host records. Queueing 'mx2.forwardemail.net' for further resolution.]
10/05/2019 06:10:45 - [Performing Additional Queries for Host records for MX Records that are queued for further resolution]
10/05/2019 06:10:45 - [Found an A Host Record for 'mx1.forwardemail.net' of '178.128.149.101']
10/05/2019 06:10:45 - [Found an A Host Record for 'mx2.forwardemail.net' of '178.128.149.101']
10/05/2019 06:10:45 - [Completed Additional Queries for Host records]
10/05/2019 06:10:45 - [DNS Session completed]
10/05/2019 06:10:45 - [Found 2 responsible mail servers for 'lucaseverett.email']
10/05/2019 06:10:47 - [Selected target email server to test 'First Available']
10/05/2019 06:10:49 - [Starting SMTP Session]
10/05/2019 06:10:49 - [Attempting to connect to 'mx1.forwardemail.net/178.128.149.101']
10/05/2019 06:10:49 - [Connecting to 178.128.149.101:25.]
10/05/2019 06:10:49 - [Connected, localEP='108.60.212.145:58027'; remoteEP='178.128.149.101:25'.]
10/05/2019 06:10:49 - 550 [108.60.212.145] is not a fully qualified domain name ("FQDN")
10/05/2019 06:10:49 - [Failed to connect to 'mx1.forwardemail.net/178.128.149.101']
10/05/2019 06:10:49 - [Attempting to connect to 'mx2.forwardemail.net/178.128.149.101']
10/05/2019 06:10:49 - [Failed to connect to 'mx2.forwardemail.net/178.128.149.101']
10/05/2019 06:10:51 - [Attempting to transmit 'helo/ehlo']
10/05/2019 06:10:51 - EHLO IsMyEmailWorking.com
10/05/2019 06:10:51 -
10/05/2019 06:10:51 - [Exception: Value cannot be null. Parameter name: line]
10/05/2019 06:10:51 - ['helo/ehlo' transmission failed]
10/05/2019 06:10:51 - [Attempting to disconnect]
10/05/2019 06:10:51 - QUIT
10/05/2019 06:10:51 - [Remote host closed connection.]
10/05/2019 06:10:51 - [Disconnected.]
10/05/2019 06:10:51 - [Disconnect success, SMTP Session terminated]

**Comment by lucaseverett** [comment]
I tried sending myself an email from another Gmail account I have access to, and I received the following error.


> Message not delivered   There was a problem delivering your message to lucas@lucaseverett.com. See the technical details below, or try resending in a few minutes
> 
> The response from the remote server was:  550 [209.85.222.175] is not a fully qualified domain name ("FQDN")

**Comment by lucaseverett** [comment]
This appears to be related to #174.

**Comment by kmpm** [comment]
Which domain is not working that should be forwarded? Both lucaseverett.com and .email point to mailgun and have no DNS config showing anything related to forwardemail at all. So if it's any of those that should be used for forwarding then it can't work. 
I might have missed something though.

**Comment by lucaseverett** [comment]
I've switched everything over to Mailgun within the last 30 minutes, as I no longer trust this forwarding service. And now that I've switched to Mailgun, some of the test emails that I sent myself earlier, prior to making the change to Mailgun, are starting to come through.

**Comment by kmpm** [comment]
That's why then. I haven't had any issues with the service today, I even got the notifications about this issue through it but... ismyemailworking.com could not send to me either but github can and so can some other services at least. 
I just thought I would test from my end to help but I couldn't achieve much it seems. Good luck anyways.

**Comment by lucaseverett** [comment]
Now that I've switched to Mailgun, ismyemailworking.com comes through to me immediately. Also, I've just received more of the test emails I sent myself a few hours ago, so the server for my work email must have been attempting to resend all of this time.

**Comment by kmpm** [comment]
This is really strange and probably confirms your issue.
```
Protonmail - forwardemail - gmail = ok
O365 - forwardemail - gmail = ok
GSuite - forwardemail - gmail = ok
Gmail(separate) - forwardemail = 550 [209.85.222.182] is not a fully qualified domain name ("FQDN")
```

**Comment by milomir-rs** [comment]
I have the same problem. 
550 [209.85.161.41] is not a fully qualified domain name ("FQDN")

@lucaseverett  Found any solution?

**Comment by niftylettuce** [comment]
Closed - please follow https://github.com/forwardemail/free-email-forwarding-service/issues/174

**Comment by niftylettuce** [comment]
I've resolved this issue and deployed a fix just now to production.  Emails should go through OK.  Gmail apparently decided to stop using FQDN as their sending IP addresses in the past 24-48 hours for some reason, I am uncertain 🙃
